[user]
name = "Kamal Al Marhubi"
email = "kamal@marhubi.com"

[ui]
default-command = "log"
pager = "delta --side-by-side"
diff-formatter = ":git"

[aliases]
hunk = ["util", "exec", "--", "jj-hunk"]

[revset-aliases]
'incomplete()' = '''empty() | description(exact:'') | description(regex-i:'^(wip|tktk)\b')'''

[revsets]
bookmark-advance-to = "heads(::@ ~ incomplete())"

[git]
private-commits = "incomplete() & mine()"

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]
diff-args = ["--side-by-side", "$left", "$right", "--width=$width"]
