query($owner:String!,$name:String!,$cursor:String){repository(owner:$owner,name:$name){pullRequests(first:10,after:$cursor,states:[OPEN,CLOSED]){nodes{id number headRefName headRefOid baseRefName baseRefOid stack{id number} timelineItems(first:100,itemTypes:[BASE_REF_CHANGED_EVENT]){nodes{__typename ... on BaseRefChangedEvent{id createdAt actor{login} previousRefName currentRefName}} pageInfo{hasNextPage hasPreviousPage startCursor endCursor}}}pageInfo{hasNextPage hasPreviousPage startCursor endCursor}}}}
