return {
  "NMAC427/guess-indent.nvim",
  "akinsho/toggleterm.nvim",
  "cbochs/grapple.nvim",
  "cbochs/portal.nvim",
  "dundalek/lazy-lsp.nvim",
  "folke/neoconf.nvim",
  "folke/neodev.nvim",
  "folke/tokyonight.nvim",
  "folke/which-key.nvim",
  "ggandor/leap.nvim",
  "jedrzejboczar/possession.nvim",
  "kylechui/nvim-surround",
  "lukas-reineke/indent-blankline.nvim",
  "mrjones2014/legendary.nvim",
  "neovim/nvim-lspconfig",
  "neovim/nvim-lspconfig",
  "numToStr/Comment.nvim",
  "nvim-lua/plenary.nvim",
  "nvim-telescope/telescope.nvim",
  { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
  "nvim-tree/nvim-web-devicons",
  "nvim-treesitter/playground",
  "ruifm/gitlinker.nvim",
  "stevearc/dressing.nvim",
  "tpope/vim-unimpaired",
}
