return {
  "plan9-for-vimspace/acme-colors",
  "Lokaltog/monotone.nvim",
  { url = "https://git.goral.net.pl/mgoral/vim-bw.git" },
  "rktjmp/lush.nvim",
  "mcchrish/zenbones.nvim",
  "jedrzejboczar/possession.nvim",
  "cbochs/portal.nvim",  -- don't commit
  "cbochs/grapple.nvim",  -- don't commit
  "numToStr/Comment.nvim",
  "stevearc/dressing.nvim",
  "ruifm/gitlinker.nvim",
  "NMAC427/guess-indent.nvim",
  "lukas-reineke/indent-blankline.nvim",
  "dundalek/lazy-lsp.nvim",
  "ggandor/leap.nvim",
  "mrjones2014/legendary.nvim",
  "folke/neoconf.nvim",
  "folke/neodev.nvim",
  "neovim/nvim-lspconfig",
  "kylechui/nvim-surround",
  "nvim-treesitter/playground",
  "neovim/nvim-lspconfig",
  "nvim-lua/plenary.nvim",
  "nvim-telescope/telescope.nvim",
  { "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
  "akinsho/toggleterm.nvim",
  "nvim-tree/nvim-web-devicons",
  "tpope/vim-unimpaired",
  "folke/which-key.nvim",
}
