[ui]
agent_panel_sort = "priority"

[ui.sidebar.agents]
rows = [
  ["state_icon", "workspace", "agent"],
]

[ui.sound]
enabled = false

[theme]
# TODO(herdrdev/herdr#1307): Set to `terminal` if light terminal handling is fixed.
name = "tokyo-night-day"
auto_switch = false
